// import { faCoffee, faAppleAlt, faBeer, faCarrot, faCat, faCrow, faDog, faDragon, faFish, faFrog, faHippo, faHorse, faKiwiBird, faOtter, faPaw, faSpider } from '@fortawesome/free-solid-svg-icons';

// export const icons = [
//   faCoffee, faAppleAlt, faBeer, faCarrot, faCat, faCrow, faDog, faDragon, faFish, faFrog, faHippo, faHorse, faKiwiBird, faOtter, faPaw, faSpider,
 
// ];
import {
  faAd,
  faAddressBook,
  faAddressCard,
  faAdjust,
  faAirFreshener,
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faAllergies,
  faAmbulance,
  faAmericanSignLanguageInterpreting,
  faAnchor,
  faAngleDoubleDown,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleDoubleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAngry,
  faAnkh,
  faAppleAlt,
  faArchive,
  faArchway,
  faArrowAltCircleDown,
  faArrowAltCircleLeft,
  faArrowAltCircleRight,
  faArrowAltCircleUp,
  faArrowCircleDown,
  faArrowCircleLeft,
  faArrowCircleRight,
  faArrowCircleUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowsAlt,
  faArrowsAltH,
  faArrowsAltV,
  faAssistiveListeningSystems,
  faAsterisk,
  faAt,
  faAtlas,
  faAtom,
  faAudioDescription,
  faAward,
  faBaby,
  faBabyCarriage,
  faBackspace,
  faBackward,
  faBacon,
  faBacteria,
  faBacterium,
  faBahai,
  faBalanceScale,
  faBalanceScaleLeft,
  faBalanceScaleRight,
  faBan,
  faBandAid,
  faBarcode,
  faBars,
  faBaseballBall,
  faBasketballBall,
  faBath,
  faBatteryEmpty,
  faBatteryFull,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryThreeQuarters,
  faBed,
  faBeer,
  faBell,
  faBellSlash,
  faBezierCurve,
  faBible,
  faBicycle,
  faBiking,
  faBinoculars,
  faBiohazard,
  faBirthdayCake,
  faBlender,
  faBlenderPhone,
  faBlind,
  faBlog,
  faBold,
  faBolt,
  faBomb,
  faBone,
  faBong,
  faBook,
  faBookDead,
  faBookMedical,
  faBookOpen,
  faBookReader,
  faBookmark,
  faBorderAll,
  faBorderNone,
  faBorderStyle,
  faBowlingBall,
  faBox,
  faBoxOpen,
  faBoxTissue,
  faBoxes,
  faBraille,
  faBrain,
  faBreadSlice,
  faBriefcase,
  faBriefcaseMedical,
  faBroadcastTower,
  faBroom,
  faBrush,
  faBug,
  faBuilding,
  faBullhorn,
  faBullseye,
  faBurn,
  faBus,
  faBusAlt,
  faBusinessTime,
  faCalculator,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDay,
  faCalendarMinus,
  faCalendarPlus,
  faCalendarTimes,
  faCalendarWeek,
  faCamera,
  faCameraRetro,
  faCampground,
  faCandyCane,
  faCannabis,
  faCapsules,
  faCar,
  faCarAlt,
  faCarBattery,
  faCarCrash,
  faCarSide,
  faCaravan,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretSquareDown,
  faCaretSquareLeft,
  faCaretSquareRight,
  faCaretSquareUp,
  faCaretUp,
  faCarrot,
  faCartArrowDown,
  faCartPlus,
  faCashRegister,
  faCat,
  faCertificate,
  faChair,
  faChalkboard,
  faChalkboardTeacher,
  faChargingStation,
  faChartArea,
  faChartBar,
  faChartLine,
  faChartPie,
  faCheck,
  faCheckCircle,
  faCheckDouble,
  faCheckSquare,
  faCheese,
  faChess,
  faChessBishop,
  faChessBoard,
  faChessKing,
  faChessKnight,
  faChessPawn,
  faChessQueen,
  faChessRook,
  faChevronCircleDown,
  faChevronCircleLeft,
  faChevronCircleRight,
  faChevronCircleUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faChurch,
  faCircle,
  faCircleNotch,
  faCity,
  faClinicMedical,
  faClipboard,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faClone,
  faClosedCaptioning,
  faCloud,
  faCloudDownloadAlt,
  faCloudMeatball,
  faCloudMoon,
  faCloudMoonRain,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudSun,
  faCloudSunRain,
  faCloudUploadAlt,
  faCocktail,
  faCode,
  faCodeBranch,
  faCoffee,
  faCog,
  faCogs,
  faCoins,
  faColumns,
  faComment,
  faCommentAlt,
  faCommentDollar,
  faCommentDots,
  faCommentMedical,
  faCommentSlash,
  faComments,
  faCommentsDollar,
  faCompactDisc,
  faCompass,
  faCompress,
  faCompressAlt,
  faCompressArrowsAlt,
  faConciergeBell,
  faCookie,
  faCookieBite,
  faCopy,
  faCopyright,
  faCouch,
  faCreditCard,
  faCrop,
  faCropAlt,
  faCross,
  faCrosshairs,
  faCrow,
  faCrown,
  faCrutch,
  faCube,
  faCubes,
  faCut,
  faDatabase,
  faDeaf,
  faDemocrat,
  faDesktop,
  faDharmachakra,
  faDiagnoses,
  faDice,
  faDiceD20,
  faDiceD6,
  faDiceFive,
  faDiceFour,
  faDiceOne,
  faDiceSix,
  faDiceThree,
  faDiceTwo,
  faDigitalTachograph,
  faDirections,
  faDisease,
  faDivide,
  faDizzy,
  faDna,
  faDog,
  faDollarSign,
  faDolly,
  faDollyFlatbed,
  faDonate,
  faDoorClosed,
  faDoorOpen,
  faDotCircle,
  faDove,
  faDownload,
  faDraftingCompass,
  faDragon,
  faDrawPolygon,
  faDrum,
  faDrumSteelpan,
  faDrumstickBite,
  faDumbbell,
  faDumpster,
  faDumpsterFire,
  faDungeon,
  faEdit,
  faEgg,
  faEject,
  faEllipsisH,
  faEllipsisV,
  faEnvelope,
  faEnvelopeOpen,
  faEnvelopeOpenText,
  faEnvelopeSquare,
  faEquals,
  faEraser,
  faEthernet,
  faEuroSign,
  faExchangeAlt,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExpand,
  faExpandAlt,
  faExpandArrowsAlt,
  faExternalLinkAlt,
  faExternalLinkSquareAlt,
  faEye,
  faEyeDropper,
  faEyeSlash,
  faFan,
  faFastBackward,
  faFastForward,
  faFaucet,
  faFax,
  faFeather,
  faFeatherAlt,
  faFemale,
  faFighterJet,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileContract,
  faFileCsv,
  faFileDownload,
  faFileExcel,
  faFileExport,
  faFileImage,
  faFileImport,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileMedical,
  faFileMedicalAlt,
  faFilePdf,
  faFilePowerpoint,
  faFilePrescription,
  faFileSignature,
  faFileUpload,
  faFileVideo,
  faFileWord,
  faFill,
  faFillDrip,
  faFilm,
  faFilter,
  faFingerprint,
  faFire,
  faFireAlt,
  faFireExtinguisher,
  faFirstAid,
  faFish,
  faFistRaised,
  faFlag,
  faFlagCheckered,
  faFlagUsa,
  faFlask,
  faFlushed,
  faFolder,
  faFolderMinus,
  faFolderOpen,
  faFolderPlus,
  faFont,
  faFootballBall,
  faForward,
  faFrog,
  faFrown,
  faFrownOpen,
  faFunnelDollar,
  faFutbol,
  faGamepad,
  faGasPump,
  faGavel,
  faGem,
  faGenderless,
  faGhost,
  faGift,
  faGifts,
  faGlassCheers,
  faGlassMartini,
  faGlassMartiniAlt,
  faGlassWhiskey,
  faGlasses,
  faGlobe,
  faGlobeAfrica,
  faGlobeAmericas,
  faGlobeAsia,
  faGlobeEurope,
  faGolfBall,
  faGopuram,
  faGraduationCap,
  faGreaterThan,
  faGreaterThanEqual,
  faGrimace,
  faGrin,
  faGrinAlt,
  faGrinBeam,
  faGrinBeamSweat,
  faGrinHearts,
  faGrinSquint,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faGripHorizontal,
  faGripLines,
  faGripLinesVertical,
  faGripVertical,
  faGuitar,
  faHSquare,
  faHamburger,
  faHammer,
  faHamsa,
  faHandHolding,
  faHandHoldingHeart,
  faHandHoldingMedical,
  faHandHoldingUsd,
  faHandHoldingWater,
  faHandLizard,
  faHandMiddleFinger,
  faHandPaper,
  faHandPeace,
  faHandPointDown,
  faHandPointLeft,
  faHandPointRight,
  faHandPointUp,
  faHandPointer,
  faHandRock,
  faHandScissors,
  faHandSparkles,
  faHandSpock,
  faHands,
  faHandsHelping,
  faHandsWash,
  faHandshake,
  faHandshakeAltSlash,
  faHandshakeSlash,
  faHanukiah,
  faHardHat,
  faHashtag,
  faHatCowboy,
  faHatCowboySide,
  faHatWizard,
  faHdd,
  faHeadSideCough,
  faHeadSideCoughSlash,
  faHeadSideMask,
  faHeadSideVirus,
  faHeading,
  faHeadphones,
  faHeadphonesAlt,
  faHeadset,
  faHeart,
  faHeartBroken,
  faHeartbeat,
  faHelicopter,
  faHighlighter,
  faHiking,
  faHippo,
  faHistory,
  faHockeyPuck,
  faHollyBerry,
  faHome,
  faHorse,
  faHorseHead,
  faHospital,
  faHospitalAlt,
  faHospitalSymbol,
  faHospitalUser,
  faHotTub,
  faHotdog,
  faHotel,
  faHourglass,
  faHourglassEnd,
  faHourglassHalf,
  faHourglassStart,
  faHouseDamage,
  faHouseUser,
  faHryvnia,
  faICursor,
  faIceCream,
  faIcicles,
  faIcons,
  faIdBadge,
  faIdCard,
  faIdCardAlt,
  faIgloo,
  faImage,
  faImages,
  faInbox,
  faIndent,
  faIndustry,
  faInfinity,
  faInfo,
  faInfoCircle,
  faItalic,
  faJedi,
  faJoint,
  faJournalWhills,
  faKaaba,
  faKey,
  faKeyboard,
  faKhanda,
  faKiss,
  faKissBeam,
  faKissWinkHeart,
  faKiwiBird,
  faLandmark,
  faLanguage,
  faLaptop,
  faLaptopCode,
  faLaptopHouse,
  faLaptopMedical,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faLaughWink,
  faLayerGroup,
  faLeaf,
  faLemon,
  faLessThan,
  faLessThanEqual,
  faLevelDownAlt,
  faLevelUpAlt,
  faLifeRing,
  faLightbulb,
  faLink,
  faLiraSign,
  faList,
  faListAlt,
  faListOl,
  faListUl,
  faLocationArrow,
  faLock,
  faLockOpen,
  faLongArrowAltDown,
  faLongArrowAltLeft,
  faLongArrowAltRight,
  faLongArrowAltUp,
  faLowVision,
  faLuggageCart,
  faLungs,
  faLungsVirus,
  faMagic,
  faMagnet,
  faMailBulk,
  faMale,
  faMap,
  faMapMarked,
  faMapMarkedAlt,
  faMapMarker,
  faMapMarkerAlt,
  faMapPin,
  faMapSigns,
  faMarker,
  faMars,
  faMarsDouble,
  faMarsStroke,
  faMarsStrokeH,
  faMarsStrokeV,
  faMask,
  faMedal,
  faMedkit,
  faMeh,
  faMehBlank,
  faMehRollingEyes,
  faMemory,
  faMenorah,
  faMercury,
  faMeteor,
  faMicrochip,
  faMicrophone,
  faMicrophoneAlt,
  faMicrophoneAltSlash,
  faMicrophoneSlash,
  faMicroscope,
  faMinus,
  faMinusCircle,
  faMinusSquare,
  faMitten,
  faMobile,
  faMobileAlt,
  faMoneyBill,
  faMoneyBillAlt,
  faMoneyBillWave,
  faMoneyBillWaveAlt,
  faMoneyCheck,
  faMoneyCheckAlt,
  faMonument,
  faMoon,
  faMortarPestle,
  faMosque,
  faMotorcycle,
  faMountain,
  faMouse,
  faMousePointer,
  faMugHot,
  faMusic,
  faNetworkWired,
  faNeuter,
  faNewspaper,
  faNotEqual,
  faNotesMedical,
  faObjectGroup,
  faObjectUngroup,
  faOilCan,
  faOm,
  faOtter,
  faOutdent,
  faPager,
  faPaintBrush,
  faPaintRoller,
  faPalette,
  faPallet,
  faPaperPlane,
  faPaperclip,
  faParachuteBox,
  faParagraph,
  faParking,
  faPassport,
  faPastafarianism,
  faPaste,
  faPause,
  faPauseCircle,
  faPaw,
  faPeace,
  faPen,
  faPenAlt,
  faPenFancy,
  faPenNib,
  faPenSquare,
  faPencilAlt,
  faPencilRuler,
  faPeopleArrows,
  faPeopleCarry,
  faPepperHot,
  faPercent,
  faPercentage,
  faPersonBooth,
  faPhone,
  faPhoneAlt,
  faPhoneSlash,
  faPhoneSquare,
  faPhoneSquareAlt,
  faPhoneVolume,
  faPhotoVideo,
  faPiggyBank,
  faPills,
  faPizzaSlice,
  faPlaceOfWorship,
  faPlane,
  faPlaneArrival,
  faPlaneDeparture,
  faPlaneSlash,
  faPlay,
  faPlayCircle,
  faPlug,
  faPlus,
  faPlusCircle,
  faPlusSquare,
  faPodcast,
  faPoll,
  faPollH,
  faPoo,
  faPooStorm,
  faPoop,
  faPortrait,
  faPoundSign,
  faPowerOff,
  faPray,
  faPrayingHands,
  faPrescription,
  faPrescriptionBottle,
  faPrescriptionBottleAlt,
  faPrint,
  faProcedures,
  faProjectDiagram,
  faPumpMedical,
  faPumpSoap,
  faPuzzlePiece,
  faQrcode,
  faQuestion,
  faQuestionCircle,
  faQuidditch,
  faQuoteLeft,
  faQuoteRight,
  faQuran,
  faRadiation,
  faRadiationAlt,
  faRainbow,
  faRandom,
  faReceipt,
  faRecordVinyl,
  faRecycle,
  faRedo,
  faRedoAlt,
  faRegistered,
  faRemoveFormat,
  faReply,
  faReplyAll,
  faRepublican,
  faRestroom,
  faRetweet,
  faRibbon,
  faRing,
  faRoad,
  faRobot,
  faRocket,
  faRoute,
  faRss,
  faRssSquare,
  faRubleSign,
  faRuler,
  faRulerCombined,
  faRulerHorizontal,
  faRulerVertical,
  faRunning,
  faRupeeSign,
  faSadCry,
  faSadTear,
  faSatellite,
  faSatelliteDish,
  faSave,
  faSchool,
  faScrewdriver,
  faScroll,
  faSdCard,
  faSearch,
  faSearchDollar,
  faSearchLocation,
  faSearchMinus,
  faSearchPlus,
  faSeedling,
  faServer,
  faShapes,
  faShare,
  faShareAlt,
  faShareAltSquare,
  faShareSquare,
  faShekelSign,
  faShieldAlt,
  faShieldVirus,
  faShip,
  faShippingFast,
  faShoePrints,
  faShoppingBag,
  faShoppingBasket,
  faShoppingCart,
  faShower,
  faShuttleVan,
  faSign,
  faSignInAlt,
  faSignLanguage,
  faSignOutAlt,
  faSignal,
  faSignature,
  faSimCard,
  faSink,
  faSitemap,
  faSkating,
  faSkiing,
  faSkiingNordic,
  faSkull,
  faSkullCrossbones,
  faSlash,
  faSleigh,
  faSlidersH,
  faSmile,
  faSmileBeam,
  faSmileWink,
  faSmog,
  faSmoking,
  faSmokingBan,
  faSms,
  faSnowboarding,
  faSnowflake,
  faSnowman,
  faSnowplow,
  faSoap,
  faSocks,
  faSolarPanel,
  faSort,
  faSortAlphaDown,
  faSortAlphaDownAlt,
  faSortAlphaUp,
  faSortAlphaUpAlt,
  faSortAmountDown,
  faSortAmountDownAlt,
  faSortAmountUp,
  faSortAmountUpAlt,
  faSortDown,
  faSortNumericDown,
  faSortNumericDownAlt,
  faSortNumericUp,
  faSortNumericUpAlt,
  faSortUp,
  faSpa,
  faSpaceShuttle,
  faSpellCheck,
  faSpider,
  faSpinner,
  faSplotch,
  faSprayCan,
  faSquare,
  faSquareFull,
  faSquareRootAlt,
  faStamp,
  faStar,
  faStarAndCrescent,
  faStarHalf,
  faStarHalfAlt,
  faStarOfDavid,
  faStarOfLife,
  faStepBackward,
  faStepForward,
  faStethoscope,
  faStickyNote,
  faStop,
  faStopCircle,
  faStopwatch,
  faStopwatch20,
  faStore,
  faStoreAlt,
  faStoreAltSlash,
  faStoreSlash,
  faStream,
  faStreetView,
  faStrikethrough,
  faStroopwafel,
  faSubscript,
  faSubway,
  faSuitcase,
  faSuitcaseRolling,
  faSun,
  faSuperscript,
  faSurprise,
  faSwatchbook,
  faSwimmer,
  faSwimmingPool,
  faSynagogue,
  faSync,
  faSyncAlt,
  faSyringe,
  faTable,
  faTableTennis,
  faTablet,
  faTabletAlt,
  faTablets,
  faTachometerAlt,
  faTag,
  faTags,
  faTape,
  faTasks,
  faTaxi,
  faTeeth,
  faTeethOpen,
  faTemperatureHigh,
  faTemperatureLow,
  faTenge,
  faTerminal,
  faTextHeight,
  faTextWidth,
  faTh,
  faThLarge,
  faThList,
  faTheaterMasks,
  faThermometer,
  faThermometerEmpty,
  faThermometerFull,
  faThermometerHalf,
  faThermometerQuarter,
  faThermometerThreeQuarters,
  faThumbsDown,
  faThumbsUp,
  faThumbtack,
  faTicketAlt,
  faTimes,
  faTimesCircle,
  faTint,
  faTintSlash,
  faTired,
  faToggleOff,
  faToggleOn,
  faToilet,
  faToiletPaper,
  faToiletPaperSlash,
  faToolbox,
  faTools,
  faTooth,
  faTorah,
  faToriiGate,
  faTractor,
  faTrademark,
  faTrafficLight,
  faTrailer,
  faTrain,
  faTram,
  faTransgender,
  faTransgenderAlt,
  faTrash,
  faTrashAlt,
  faTrashRestore,
  faTrashRestoreAlt,
  faTree,
  faTrophy,
  faTruck,
  faTruckLoading,
  faTruckMonster,
  faTruckMoving,
  faTruckPickup,
  faTshirt,
  faTty,
  faTv,
  faUmbrella,
  faUmbrellaBeach,
  faUnderline,
  faUndo,
  faUndoAlt,
  faUniversalAccess,
  faUniversity,
  faUnlink,
  faUnlock,
  faUnlockAlt,
  faUpload,
  faUser,
  faUserAlt,
  faUserAltSlash,
  faUserAstronaut,
  faUserCheck,
  faUserCircle,
  faUserClock,
  faUserCog,
  faUserEdit,
  faUserFriends,
  faUserGraduate,
  faUserInjured,
  faUserLock,
  faUserMd,
  faUserMinus,
  faUserNinja,
  faUserNurse,
  faUserPlus,
  faUserSecret,
  faUserShield,
  faUserSlash,
  faUserTag,
  faUserTie,
  faUserTimes,
  faUsers,
  faUsersCog,
  faUsersSlash,
  faUtensilSpoon,
  faUtensils,
  faVectorSquare,
  faVenus,
  faVenusDouble,
  faVenusMars,
  faVest,
  faVestPatches,
  faVial,
  faVials,
  faVideo,
  faVideoSlash,
  faVihara,
  faVirus,
  faVirusSlash,
  faViruses,
  faVoicemail,
  faVolleyballBall,
  faVolumeDown,
  faVolumeMute,
  faVolumeOff,
  faVolumeUp,
  faVoteYea,
  faVrCardboard,
  faWalking,
  faWallet,
  faWarehouse,
  faWater,
  faWaveSquare,
  faWeight,
  faWeightHanging,
  faWheelchair,
  faWifi,
  faWind,
  faWindowClose,
  faWindowMaximize,
  faWindowMinimize,
  faWindowRestore,
  faWineBottle,
  faWineGlass,
  faWineGlassAlt,
  faWonSign,
  faWrench,
  faXRay,
  faYenSign,
  faYinYang,
} from '@fortawesome/free-solid-svg-icons';

export const icons = [
  { icon: faAd, name: 'faAd' },
  { icon: faAddressBook, name: 'faAddressBook' },
  { icon: faAddressCard, name: 'faAddressCard' },
  { icon: faAdjust, name: 'faAdjust' },
  { icon: faAirFreshener, name: 'faAirFreshener' },
  { icon: faAlignCenter, name: 'faAlignCenter' },
  { icon: faAlignJustify, name: 'faAlignJustify' },
  { icon: faAlignLeft, name: 'faAlignLeft' },
  { icon: faAlignRight, name: 'faAlignRight' },
  { icon: faAllergies, name: 'faAllergies' },
  { icon: faAmbulance, name: 'faAmbulance' },
  { icon: faAmericanSignLanguageInterpreting, name: 'faAmericanSignLanguageInterpreting' },
  { icon: faAnchor, name: 'faAnchor' },
  { icon: faAngleDoubleDown, name: 'faAngleDoubleDown' },
  { icon: faAngleDoubleLeft, name: 'faAngleDoubleLeft' },
  { icon: faAngleDoubleRight, name: 'faAngleDoubleRight' },
  { icon: faAngleDoubleUp, name: 'faAngleDoubleUp' },
  { icon: faAngleDown, name: 'faAngleDown' },
  { icon: faAngleLeft, name: 'faAngleLeft' },
  { icon: faAngleRight, name: 'faAngleRight' },
  { icon: faAngleUp, name: 'faAngleUp' },
  { icon: faAngry, name: 'faAngry' },
  { icon: faAnkh, name: 'faAnkh' },
  { icon: faAppleAlt, name: 'faAppleAlt' },
  { icon: faArchive, name: 'faArchive' },
  { icon: faArchway, name: 'faArchway' },
  { icon: faArrowAltCircleDown, name: 'faArrowAltCircleDown' },
  { icon: faArrowAltCircleLeft, name: 'faArrowAltCircleLeft' },
  { icon: faArrowAltCircleRight, name: 'faArrowAltCircleRight' },
  { icon: faArrowAltCircleUp, name: 'faArrowAltCircleUp' },
  { icon: faArrowCircleDown, name: 'faArrowCircleDown' },
  { icon: faArrowCircleLeft, name: 'faArrowCircleLeft' },
  { icon: faArrowCircleRight, name: 'faArrowCircleRight' },
  { icon: faArrowCircleUp, name: 'faArrowCircleUp' },
  { icon: faArrowDown, name: 'faArrowDown' },
  { icon: faArrowLeft, name: 'faArrowLeft' },
  { icon: faArrowRight, name: 'faArrowRight' },
  { icon: faArrowUp, name: 'faArrowUp' },
  { icon: faArrowsAlt, name: 'faArrowsAlt' },
  { icon: faArrowsAltH, name: 'faArrowsAltH' },
  { icon: faArrowsAltV, name: 'faArrowsAltV' },
  { icon: faAssistiveListeningSystems, name: 'faAssistiveListeningSystems' },
  { icon: faAsterisk, name: 'faAsterisk' },
  { icon: faAt, name: 'faAt' },
  { icon: faAtlas, name: 'faAtlas' },
  { icon: faAtom, name: 'faAtom' },
  { icon: faAudioDescription, name: 'faAudioDescription' },
  { icon: faAward, name: 'faAward' },
  { icon: faBaby, name: 'faBaby' },
  { icon: faBabyCarriage, name: 'faBabyCarriage' },
  { icon: faBackspace, name: 'faBackspace' },
  { icon: faBackward, name: 'faBackward' },
  { icon: faBacon, name: 'faBacon' },
  { icon: faBacteria, name: 'faBacteria' },
  { icon: faBacterium, name: 'faBacterium' },
  { icon: faBahai, name: 'faBahai' },
  { icon: faBalanceScale, name: 'faBalanceScale' },
  { icon: faBalanceScaleLeft, name: 'faBalanceScaleLeft' },
  { icon: faBalanceScaleRight, name: 'faBalanceScaleRight' },
  { icon: faBan, name: 'faBan' },
  { icon: faBandAid, name: 'faBandAid' },
  { icon: faBarcode, name: 'faBarcode' },
  { icon: faBars, name: 'faBars' },
  { icon: faBaseballBall, name: 'faBaseballBall' },
  { icon: faBasketballBall, name: 'faBasketballBall' },
  { icon: faBath, name: 'faBath' },
  { icon: faBatteryEmpty, name: 'faBatteryEmpty' },
  { icon: faBatteryFull, name: 'faBatteryFull' },
  { icon: faBatteryHalf, name: 'faBatteryHalf' },
  { icon: faBatteryQuarter, name: 'faBatteryQuarter' },
  { icon: faBatteryThreeQuarters, name: 'faBatteryThreeQuarters' },
  { icon: faBed, name: 'faBed' },
  { icon: faBeer, name: 'faBeer' },
  { icon: faBell, name: 'faBell' },
  { icon: faBellSlash, name: 'faBellSlash' },
  { icon: faBezierCurve, name: 'faBezierCurve' },
  { icon: faBible, name: 'faBible' },
  { icon: faBicycle, name: 'faBicycle' },
  { icon: faBiking, name: 'faBiking' },
  { icon: faBinoculars, name: 'faBinoculars' },
  { icon: faBiohazard, name: 'faBiohazard' },
  { icon: faBirthdayCake, name: 'faBirthdayCake' },
  { icon: faBlender, name: 'faBlender' },
  { icon: faBlenderPhone, name: 'faBlenderPhone' },
  { icon: faBlind, name: 'faBlind' },
  { icon: faBlog, name: 'faBlog' },
  { icon: faBold, name: 'faBold' },
  { icon: faBolt, name: 'faBolt' },
  { icon: faBomb, name: 'faBomb' },
  { icon: faBone, name: 'faBone' },
  { icon: faBong, name: 'faBong' },
  { icon: faBook, name: 'faBook' },
  { icon: faBookDead, name: 'faBookDead' },
  { icon: faBookMedical, name: 'faBookMedical' },
  { icon: faBookOpen, name: 'faBookOpen' },
  { icon: faBookReader, name: 'faBookReader' },
  { icon: faBookmark, name: 'faBookmark' },
  { icon: faBorderAll, name: 'faBorderAll' },
  { icon: faBorderNone, name: 'faBorderNone' },
  { icon: faBorderStyle, name: 'faBorderStyle' },
  { icon: faBowlingBall, name: 'faBowlingBall' },
  { icon: faBox, name: 'faBox' },
  { icon: faBoxOpen, name: 'faBoxOpen' },
  { icon: faBoxTissue, name: 'faBoxTissue' },
  { icon: faBoxes, name: 'faBoxes' },
  { icon: faBraille, name: 'faBraille' },
  { icon: faBrain, name: 'faBrain' },
  { icon: faBreadSlice, name: 'faBreadSlice' },
  { icon: faBriefcase, name: 'faBriefcase' },
  { icon: faBriefcaseMedical, name: 'faBriefcaseMedical' },
  { icon: faBroadcastTower, name: 'faBroadcastTower' },
  { icon: faBroom, name: 'faBroom' },
  { icon: faBrush, name: 'faBrush' },
  { icon: faBug, name: 'faBug' },
  { icon: faBuilding, name: 'faBuilding' },
  { icon: faBullhorn, name: 'faBullhorn' },
  { icon: faBullseye, name: 'faBullseye' },
  { icon: faBurn, name: 'faBurn' },
  { icon: faBus, name: 'faBus' },
  { icon: faBusAlt, name: 'faBusAlt' },
  { icon: faBusinessTime, name: 'faBusinessTime' },
  { icon: faCalculator, name: 'faCalculator' },
  { icon: faCalendar, name: 'faCalendar' },
  { icon: faCalendarAlt, name: 'faCalendarAlt' },
  { icon: faCalendarCheck, name: 'faCalendarCheck' },
  { icon: faCalendarDay, name: 'faCalendarDay' },
  { icon: faCalendarMinus, name: 'faCalendarMinus' },
  { icon: faCalendarPlus, name: 'faCalendarPlus' },
  { icon: faCalendarTimes, name: 'faCalendarTimes' },
  { icon: faCalendarWeek, name: 'faCalendarWeek' },
  { icon: faCamera, name: 'faCamera' },
  { icon: faCameraRetro, name: 'faCameraRetro' },
  { icon: faCampground, name: 'faCampground' },
  { icon: faCandyCane, name: 'faCandyCane' },
  { icon: faCannabis, name: 'faCannabis' },
  { icon: faCapsules, name: 'faCapsules' },
  { icon: faCar, name: 'faCar' },
  { icon: faCarAlt, name: 'faCarAlt' },
  { icon: faCarBattery, name: 'faCarBattery' },
  { icon: faCarCrash, name: 'faCarCrash' },
  { icon: faCarSide, name: 'faCarSide' },
  { icon: faCaravan, name: 'faCaravan' },
  { icon: faCaretDown, name: 'faCaretDown' },
  { icon: faCaretLeft, name: 'faCaretLeft' },
  { icon: faCaretRight, name: 'faCaretRight' },
  { icon: faCaretSquareDown, name: 'faCaretSquareDown' },
  { icon: faCaretSquareLeft, name: 'faCaretSquareLeft' },
  { icon: faCaretSquareRight, name: 'faCaretSquareRight' },
  { icon: faCaretSquareUp, name: 'faCaretSquareUp' },
  { icon: faCaretUp, name: 'faCaretUp' },
  { icon: faCarrot, name: 'faCarrot' },
  { icon: faCartArrowDown, name: 'faCartArrowDown' },
  { icon: faCartPlus, name: 'faCartPlus' },
  { icon: faCashRegister, name: 'faCashRegister' },
  { icon: faCat, name: 'faCat' },
  { icon: faCertificate, name: 'faCertificate' },
  { icon: faChair, name: 'faChair' },
  { icon: faChalkboard, name: 'faChalkboard' },
  { icon: faChalkboardTeacher, name: 'faChalkboardTeacher' },
  { icon: faChargingStation, name: 'faChargingStation' },
  { icon: faChartArea, name: 'faChartArea' },
  { icon: faChartBar, name: 'faChartBar' },
  { icon: faChartLine, name: 'faChartLine' },
  { icon: faChartPie, name: 'faChartPie' },
  { icon: faCheck, name: 'faCheck' },
  { icon: faCheckCircle, name: 'faCheckCircle' },
  { icon: faCheckDouble, name: 'faCheckDouble' },
  { icon: faCheckSquare, name: 'faCheckSquare' },
  { icon: faCheese, name: 'faCheese' },
  { icon: faChess, name: 'faChess' },
  { icon: faChessBishop, name: 'faChessBishop' },
  { icon: faChessBoard, name: 'faChessBoard' },
  { icon: faChessKing, name: 'faChessKing' },
  { icon: faChessKnight, name: 'faChessKnight' },
  { icon: faChessPawn, name: 'faChessPawn' },
  { icon: faChessQueen, name: 'faChessQueen' },
  { icon: faChessRook, name: 'faChessRook' },
  { icon: faChevronCircleDown, name: 'faChevronCircleDown' },
  { icon: faChevronCircleLeft, name: 'faChevronCircleLeft' },
  { icon: faChevronCircleRight, name: 'faChevronCircleRight' },
  { icon: faChevronCircleUp, name: 'faChevronCircleUp' },
  { icon: faChevronDown, name: 'faChevronDown' },
  { icon: faChevronLeft, name: 'faChevronLeft' },
  { icon: faChevronRight, name: 'faChevronRight' },
  { icon: faChevronUp, name: 'faChevronUp' },
  { icon: faChild, name: 'faChild' },
  { icon: faChurch, name: 'faChurch' },
  { icon: faCircle, name: 'faCircle' },
  { icon: faCircleNotch, name: 'faCircleNotch' },
  { icon: faCity, name: 'faCity' },
  { icon: faClinicMedical, name: 'faClinicMedical' },
  { icon: faClipboard, name: 'faClipboard' },
  { icon: faClipboardCheck, name: 'faClipboardCheck' },
  { icon: faClipboardList, name: 'faClipboardList' },
  { icon: faClock, name: 'faClock' },
  { icon: faClone, name: 'faClone' },
  { icon: faClosedCaptioning, name: 'faClosedCaptioning' },
  { icon: faCloud, name: 'faCloud' },
  { icon: faCloudDownloadAlt, name: 'faCloudDownloadAlt' },
  { icon: faCloudMeatball, name: 'faCloudMeatball' },
  { icon: faCloudMoon, name: 'faCloudMoon' },
  { icon: faCloudMoonRain, name: 'faCloudMoonRain' },
  { icon: faCloudRain, name: 'faCloudRain' },
  { icon: faCloudShowersHeavy, name: 'faCloudShowersHeavy' },
  { icon: faCloudSun, name: 'faCloudSun' },
  { icon: faCloudSunRain, name: 'faCloudSunRain' },
  { icon: faCloudUploadAlt, name: 'faCloudUploadAlt' },
  { icon: faCocktail, name: 'faCocktail' },
  { icon: faCode, name: 'faCode' },
  { icon: faCodeBranch, name: 'faCodeBranch' },
  { icon: faCoffee, name: 'faCoffee' },
  { icon: faCog, name: 'faCog' },
  { icon: faCogs, name: 'faCogs' },
  { icon: faCoins, name: 'faCoins' },
  { icon: faColumns, name: 'faColumns' },
  { icon: faComment, name: 'faComment' },
  { icon: faCommentAlt, name: 'faCommentAlt' },
  { icon: faCommentDollar, name: 'faCommentDollar' },
  { icon: faCommentDots, name: 'faCommentDots' },
  { icon: faCommentMedical, name: 'faCommentMedical' },
  { icon: faCommentSlash, name: 'faCommentSlash' },
  { icon: faComments, name: 'faComments' },
  { icon: faCommentsDollar, name: 'faCommentsDollar' },
  { icon: faCompactDisc, name: 'faCompactDisc' },
  { icon: faCompass, name: 'faCompass' },
  { icon: faCompress, name: 'faCompress' },
  { icon: faCompressAlt, name: 'faCompressAlt' },
  { icon: faCompressArrowsAlt, name: 'faCompressArrowsAlt' },
  { icon: faConciergeBell, name: 'faConciergeBell' },
  { icon: faCookie, name: 'faCookie' },
  { icon: faCookieBite, name: 'faCookieBite' },
  { icon: faCopy, name: 'faCopy' },
  { icon: faCopyright, name: 'faCopyright' },
  { icon: faCouch, name: 'faCouch' },
  { icon: faCreditCard, name: 'faCreditCard' },
  { icon: faCrop, name: 'faCrop' },
  { icon: faCropAlt, name: 'faCropAlt' },
  { icon: faCross, name: 'faCross' },
  { icon: faCrosshairs, name: 'faCrosshairs' },
  { icon: faCrow, name: 'faCrow' },
  { icon: faCrown, name: 'faCrown' },
  { icon: faCrutch, name: 'faCrutch' },
  { icon: faCube, name: 'faCube' },
  { icon: faCubes, name: 'faCubes' },
  { icon: faCut, name: 'faCut' },
  { icon: faDatabase, name: 'faDatabase' },
  { icon: faDeaf, name: 'faDeaf' },
  { icon: faDemocrat, name: 'faDemocrat' },
  { icon: faDesktop, name: 'faDesktop' },
  { icon: faDharmachakra, name: 'faDharmachakra' },
  { icon: faDiagnoses, name: 'faDiagnoses' },
  { icon: faDice, name: 'faDice' },
  { icon: faDiceD20, name: 'faDiceD20' },
]
